language: php

php:
  - "5.4"
  - "5.5"
  - "5.6"
  - "7.0"

matrix:
  include:
    - php: "5.3"
      dist: precise

branches:
  only:
    - master
    - /^\d+\.\d+$/

before_script:
  - composer install --dev

script: ./phpunit
